Repository cms-l1t-offline/cmssw, pull requests merged in 2023-07, with the labels that each got.

#1149 Change muon shower BX assignment in EMTF (backport of PR42176)
  L1Trigger/L1TMuonEndCap/plugins/L1TMuonEndCapShowerProducer.cc
  L1Trigger/L1TMuonEndCap/src/SectorProcessorShower.cc
Labels: Phase-1, Backport

#1150 Add BX boundary checks for BXVector push_back (backport of PR42214)
  DataFormats/L1Trigger/BuildFile.xml
  DataFormats/L1Trigger/interface/BXVector.icc
Labels: Phase-1, Backport

#1130 Phase 2 fastHistoEmulation updated to 256 bins, with associated Track Selection changes
  DQMOffline/L1Trigger/python/L1TPhase2Offline_cfi.py
  L1Trigger/Configuration/python/SimL1Emulator_cff.py
  L1Trigger/DemonstratorTools/plugins/GTTFileWriter.cc
  L1Trigger/DemonstratorTools/python/l1tGTTFileReader_cfi.py
  L1Trigger/DemonstratorTools/python/l1tGTTFileWriter_cfi.py
  L1Trigger/DemonstratorTools/test/gtt/createFirmwareInputFiles_cfg.py
  L1Trigger/DemonstratorTools/test/gtt/verifyFirmwareOutput_cfg.py
  L1Trigger/L1TNtuples/plugins/L1PhaseIITreeProducer.cc
  L1Trigger/L1TNtuples/plugins/L1PhaseIITreeStep1Producer.cc
  L1Trigger/L1TNtuples/python/l1PhaseIITreeProducer_cfi.py
  L1Trigger/L1TNtuples/python/l1PhaseIITreeStep1Producer_cfi.py
  L1Trigger/L1TTrackMatch/plugins/L1FastTrackingJetProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TrackJetEmulatorProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TrackJetProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TrackSelectionProducer.cc
  L1Trigger/L1TTrackMatch/plugins/L1TrackVertexAssociationProducer.cc
  L1Trigger/L1TTrackMatch/python/L1TkMETAnalyser_cfi.py
  L1Trigger/L1TTrackMatch/python/L1TkObjectProducers_cff.py
  L1Trigger/L1TTrackMatch/python/l1tFastTrackingJetProducer_cfi.py
  L1Trigger/L1TTrackMatch/python/l1tTrackFastJets_cfi.py
  L1Trigger/L1TTrackMatch/python/l1tTrackJetsEmulation_cfi.py
  L1Trigger/L1TTrackMatch/python/l1tTrackJets_cfi.py
  L1Trigger/L1TTrackMatch/python/l1tTrackSelectionProducer_cfi.py
  L1Trigger/L1TTrackMatch/python/l1tTrackVertexAssociationProducer_cfi.py
  L1Trigger/L1TTrackMatch/python/l1tTrackerEmuEtMiss_cfi.py
  L1Trigger/L1TTrackMatch/python/l1tTrackerEtMiss_cfi.py
  L1Trigger/L1TTrackMatch/python/l1tTrackerHTMiss_cfi.py
  L1Trigger/L1TTrackMatch/test/L1TrackMET_cfg.py
  L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker.cc
  L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker_cfg.py
  L1Trigger/Phase2L1ParticleFlow/plugins/L1BJetPFJetProducer.cc
  L1Trigger/Phase2L1ParticleFlow/python/L1BJetProducer_cff.py
  L1Trigger/Phase2L1ParticleFlow/python/l1ctLayer1_cff.py
  L1Trigger/Phase2L1ParticleFlow/test/make_l1ctLayer1_dumpFiles_cfg.py
  L1Trigger/Phase2L1ParticleFlow/test/make_l1ct_patternFiles_cfg.py
  L1Trigger/Phase2L1Taus/plugins/HPSPFTauProducer.cc
  L1Trigger/Phase2L1Taus/python/l1emulator_cff.py
  L1Trigger/VertexFinder/interface/VertexProducer.h
  L1Trigger/VertexFinder/plugins/VertexProducer.cc
  L1Trigger/VertexFinder/python/l1tVertexNTupler_cfi.py
  L1Trigger/VertexFinder/python/l1tVertexProducer_cfi.py
  L1Trigger/VertexFinder/src/VertexFinder.cc
  L1Trigger/VertexFinder/test/vertexNTupler_cfg.py
Labels: URGENT, Phase-2, Emulator Development

#1153 Add caloParams_2023_v0_4_cfi
  L1Trigger/L1TCalorimeter/python/caloParams_2023_v0_4_cfi.py
Labels: Phase-1, Configuration

#1151 Phase 2 match GTTFileWriter cfi and source parameter name
  L1Trigger/DemonstratorTools/python/l1tGTTFileWriter_cfi.py
Labels: Phase-2, Configuration

#1152 Phase 2 GTT inversion LUT harmonization
  L1Trigger/VertexFinder/src/VertexFinder.cc
Labels: Phase-2, Emulator Development
